name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd "Semester 4/Quality Assurance And Testing/Assignment 6"
          dotnet restore testProject.csproj

      - name: Build the project
        run: |
          cd "Semester 4/Quality Assurance And Testing/Assignment 6"
          dotnet build testProject.csproj --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: "Semester 4/Quality Assurance And Testing/Assignment 6/bin/Release/"
